version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: src/main/Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=cryptodrink
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - web

  frontend:
    build:
      context: ./frontend
    ports:
      - "80"
    networks:
      - web

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - web

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cryptodrink
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      retries: 5
      start_period: 30s
      timeout: 5s
    networks:
      - web

networks:
  web:

volumes:
  postgres_data:
    external: true
    name: cryptodrink_db
