version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: src/main/Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=cryptodrink
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - web

  frontend:
    build:
      context: ./frontend
    container_name: crypto-drink-frontend-1
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/nginx/conf.d:/etc/nginx/conf.d
        # ports:
        #   - "80"
    depends_on:
      - backend
    networks:
      - web

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cryptodrink
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      retries: 5
      start_period: 30s
      timeout: 5s
    networks:
      - web

networks:
  web:
    external: true

volumes:
  postgres_data:
    external: true
    name: cryptodrink_db
